{
  imports = [
    ./actual
    ./adguardhome
    ./audiobookshelf
    ./bitcoin
    ./firefly-iii
    ./filebrowser
    ./forgejo
    ./grocy
    ./headscale
    ./headplane
    ./home-assistant
    ./homebox
    ./icecast
    ./immich
    ./invidious
    ./jellyfin
    ./jitsi-meet
    ./kavita
    ./llm
    ./mail
    ./navidrome
    ./nextcloud
    ./owntracks
    ./openclaw
    ./opensave
    ./openwebrx
    ./openwebui
    ./radio-streams
    ./radicale
    ./realtime
    ./remote-desktop
    ./roundcube
    ./searxng
    ./sunshine
    ./syncthing
    ./tvheadend
    ./vaultwarden
    ./wol-bridge
    ./xmpp
  ];
}
