{
  imports = [
    ./pkgs.nix
    ./system.nix
    ./power.nix
    ./users.nix
    ./desktop
    ./network/ssh.nix
    ./network/wireguard.nix
    ./network/ddns.nix
    ./network/tailscale.nix
    ./services/bitcoin.nix
    ./services/filebrowser.nix
    ./services/llm.nix
    ./services/openclaw.nix
    ./services/remote-desktop.nix
    ./services/sunshine.nix
  ];
}
