{
  imports = [
    ./cluster
    ./pkgs.nix
    ./system.nix
    ./power.nix
    ./users.nix
    ./desktop
    ./network/ssh.nix
    ./network/wireguard.nix
    ./network/ddns.nix
    ./network/tailscale.nix
    ./network/wifi.nix
    ./network/tor.nix
    ./services/filebrowser.nix
    ./services/forgejo.nix
    ./services/immich.nix
    ./services/invidious.nix
    ./services/jellyfin.nix
    ./services/llm.nix
    ./services/nextcloud.nix
    ./services/openclaw.nix
    ./services/openwebui.nix
    ./services/radicale.nix
    ./services/remote-desktop.nix
    ./services/searxng.nix
    ./services/sunshine.nix
    ./services/syncthing.nix
    ./services/tvheadend.nix
    ./services/vaultwarden.nix
  ];
}
