creation_rules:
- age:
  - age1w6a0h33yazg69vdupphhxjk3a6rdmgq5qz6c4l2d637j3grzsclqxyyl7k
  - age16ca65fwnny3tjk890qvpmq5hu933auwzfjhzrupz50muynh7wc6q8z9n2c
  - age1xgpfqft6xks6qh0r29lqh2pmau6mhklqd5q8ylynmlevmemss4qsfs8tnv
  - age1fmjf2c6alaquxg558rgmrukswvfelxpq4jrr6tc8kvpe7xg07ulsa4tu7p
  - age14hvqw052wzn8wlxrevzlgydthcenjc7jh4t76gwqljglknj6maash22pl5
  - age1xlpujktcrv84rx498z7wakal4c4pklda2c2s4jx2kgxsh2yaa9lq6v7ptk
  - age1c39ghy9vgh2l0hkjv26r7jwgkw9s80yc5w8pa400cvp7ugdy5yfqv5z4vj
  path_regex: ^secrets/.*\.ya?ml$
