creation_rules:
  - path_regex: secrets/.*\.ya?ml$
    age:
      - age1xp0mwp3fh74d2wxftxpyv0z04z60hdm98vqw4muxemvuqt64653seljhr3
      - age1xgpfqft6xks6qh0r29lqh2pmau6mhklqd5q8ylynmlevmemss4qsfs8tnv