{ config, lib, pkgs-unstable, ... }:

let
  cfg = config.dolphin;
in
{
  options.dolphin.enable = lib.mkEnableOption "Dolphin Emulator for this user";

  config.home.modules = lib.optionals cfg.enable [
    {
      home.packages = [ pkgs-unstable.dolphin-emu ];

      xdg.configFile."dolphin-emu/Profiles/Wiimote/MarioKartX360.ini".text = ''
        [Profile]
        Device = SDL/0/X360 Controller
        Buttons/A = `Button E`
        Buttons/B = `Trigger R`
        Buttons/1 = `Button S`
        Buttons/2 = `Button W`
        Buttons/- = Back
        Buttons/+ = Start
        Buttons/Home = Guide
        D-Pad/Up = `Pad N`
        D-Pad/Down = `Pad S`
        D-Pad/Left = `Pad W`
        D-Pad/Right = `Pad E`
        IR/Up = `Cursor Y-`
        IR/Down = `Cursor Y+`
        IR/Left = `Cursor X-`
        IR/Right = `Cursor X+`
        Shake/X = `Click 2`
        Shake/Y = `Click 2`
        Shake/Z = `Click 2`
        IRPassthrough/Object 1 X = `IR Object 1 X`
        IRPassthrough/Object 1 Y = `IR Object 1 Y`
        IRPassthrough/Object 1 Size = `IR Object 1 Size`
        IRPassthrough/Object 2 X = `IR Object 2 X`
        IRPassthrough/Object 2 Y = `IR Object 2 Y`
        IRPassthrough/Object 2 Size = `IR Object 2 Size`
        IRPassthrough/Object 3 X = `IR Object 3 X`
        IRPassthrough/Object 3 Y = `IR Object 3 Y`
        IRPassthrough/Object 3 Size = `IR Object 3 Size`
        IRPassthrough/Object 4 X = `IR Object 4 X`
        IRPassthrough/Object 4 Y = `IR Object 4 Y`
        IRPassthrough/Object 4 Size = `IR Object 4 Size`
        IMUAccelerometer/Up = `Accel Up`
        IMUAccelerometer/Down = `Accel Down`
        IMUAccelerometer/Left = `Accel Left`
        IMUAccelerometer/Right = `Accel Right`
        IMUAccelerometer/Forward = `Accel Forward`
        IMUAccelerometer/Backward = `Accel Backward`
        IMUGyroscope/Pitch Up = `Gyro Pitch Up`
        IMUGyroscope/Pitch Down = `Gyro Pitch Down`
        IMUGyroscope/Roll Left = `Gyro Roll Left`
        IMUGyroscope/Roll Right = `Gyro Roll Right`
        IMUGyroscope/Yaw Left = `Gyro Yaw Left`
        IMUGyroscope/Yaw Right = `Gyro Yaw Right`
        Extension = Nunchuk
        Nunchuk/Buttons/C = `Button N`
        Nunchuk/Buttons/Z = `Trigger L`
        Nunchuk/Stick/Up = `Left Y+`
        Nunchuk/Stick/Down = `Left Y-`
        Nunchuk/Stick/Left = `Left X-`
        Nunchuk/Stick/Right = `Left X+`
        Nunchuk/Stick/Calibration = 100.00 141.42 100.00 141.42 100.00 141.42 100.00 141.42
        Nunchuk/Shake/X = `Click 2`
        Nunchuk/Shake/Y = `Click 2`
        Nunchuk/Shake/Z = `Click 2`
      '';

      xdg.configFile."dolphin-emu/Profiles/Wiimote/MarioKartKeyboard.ini".text = ''
        [Profile]
        Device = XInput2/0/Virtual core pointer
        Buttons/A = W
        Buttons/B = Shift
        Buttons/1 = Z
        Buttons/2 = X
        Buttons/- = Q
        Buttons/+ = E
        Buttons/Home = Return
        D-Pad/Up = Up
        D-Pad/Down = Down
        D-Pad/Left = Left
        D-Pad/Right = Right
        IR/Up = `Cursor Y-`
        IR/Down = `Cursor Y+`
        IR/Left = `Cursor X-`
        IR/Right = `Cursor X+`
        Shake/X = L
        Shake/Y = L
        Shake/Z = L
        Tilt/Backward = K
        Swing/Up = K
        IRPassthrough/Object 1 X = `IR Object 1 X`
        IRPassthrough/Object 1 Y = `IR Object 1 Y`
        IRPassthrough/Object 1 Size = `IR Object 1 Size`
        IRPassthrough/Object 2 X = `IR Object 2 X`
        IRPassthrough/Object 2 Y = `IR Object 2 Y`
        IRPassthrough/Object 2 Size = `IR Object 2 Size`
        IRPassthrough/Object 3 X = `IR Object 3 X`
        IRPassthrough/Object 3 Y = `IR Object 3 Y`
        IRPassthrough/Object 3 Size = `IR Object 3 Size`
        IRPassthrough/Object 4 X = `IR Object 4 X`
        IRPassthrough/Object 4 Y = `IR Object 4 Y`
        IRPassthrough/Object 4 Size = `IR Object 4 Size`
        IMUAccelerometer/Up = `Accel Up`
        IMUAccelerometer/Down = `Accel Down`
        IMUAccelerometer/Left = `Accel Left`
        IMUAccelerometer/Right = `Accel Right`
        IMUAccelerometer/Forward = `Accel Forward`
        IMUAccelerometer/Backward = `Accel Backward`
        IMUGyroscope/Pitch Up = `Gyro Pitch Up`
        IMUGyroscope/Pitch Down = `Gyro Pitch Down`
        IMUGyroscope/Roll Left = `Gyro Roll Left`
        IMUGyroscope/Roll Right = `Gyro Roll Right`
        IMUGyroscope/Yaw Left = `Gyro Yaw Left`
        IMUGyroscope/Yaw Right = `Gyro Yaw Right`
        Extension = Nunchuk
        Nunchuk/Buttons/C = C
        Nunchuk/Buttons/Z = J
        Nunchuk/Stick/Up = W
        Nunchuk/Stick/Down = S
        Nunchuk/Stick/Left = A
        Nunchuk/Stick/Right = D
        Nunchuk/Stick/Calibration = 100.00 141.42 100.00 141.42 100.00 141.42 100.00 141.42
        Nunchuk/Shake/X = `Click 2`
        Nunchuk/Shake/Y = `Click 2`
        Nunchuk/Shake/Z = `Click 2`
        Options/Sideways Wiimote = True
      '';

      xdg.configFile."dolphin-emu/Profiles/Wiimote/DSU-AlaniPhone.ini".text = ''
        [Profile]
        Device = DSUClient/0/AlaniPhone
        Buttons/A = Cross
        Buttons/B = Square
        Buttons/1 = Triangle
        Buttons/2 = Circle
        Buttons/- = Share
        Buttons/+ = Options
        Buttons/Home = PS
        D-Pad/Up = `Pad N`
        D-Pad/Down = `Pad S`
        D-Pad/Left = `Pad W`
        D-Pad/Right = `Pad E`
        IR/Up = `Cursor Y-`
        IR/Down = `Cursor Y+`
        IR/Left = `Cursor X-`
        IR/Right = `Cursor X+`
        Shake/X = `Click 2`
        Shake/Y = `Click 2`
        Shake/Z = `Click 2`
        IRPassthrough/Object 1 X = `IR Object 1 X`
        IRPassthrough/Object 1 Y = `IR Object 1 Y`
        IRPassthrough/Object 1 Size = `IR Object 1 Size`
        IRPassthrough/Object 2 X = `IR Object 2 X`
        IRPassthrough/Object 2 Y = `IR Object 2 Y`
        IRPassthrough/Object 2 Size = `IR Object 2 Size`
        IRPassthrough/Object 3 X = `IR Object 3 X`
        IRPassthrough/Object 3 Y = `IR Object 3 Y`
        IRPassthrough/Object 3 Size = `IR Object 3 Size`
        IRPassthrough/Object 4 X = `IR Object 4 X`
        IRPassthrough/Object 4 Y = `IR Object 4 Y`
        IRPassthrough/Object 4 Size = `IR Object 4 Size`
        IMUAccelerometer/Up = `Accel Up`
        IMUAccelerometer/Down = `Accel Down`
        IMUAccelerometer/Left = `Accel Left`
        IMUAccelerometer/Right = `Accel Right`
        IMUAccelerometer/Forward = `Accel Forward`
        IMUAccelerometer/Backward = `Accel Backward`
        IMUGyroscope/Pitch Up = `Gyro Pitch Up`
        IMUGyroscope/Pitch Down = `Gyro Pitch Down`
        IMUGyroscope/Roll Left = `Gyro Roll Left`
        IMUGyroscope/Roll Right = `Gyro Roll Right`
        IMUGyroscope/Yaw Left = `Gyro Yaw Left`
        IMUGyroscope/Yaw Right = `Gyro Yaw Right`
        Nunchuk/Buttons/C = Control_L
        Nunchuk/Buttons/Z = Shift_L
        Nunchuk/Stick/Up = W
        Nunchuk/Stick/Down = S
        Nunchuk/Stick/Left = A
        Nunchuk/Stick/Right = D
        Nunchuk/Stick/Calibration = 100.00 141.42 100.00 141.42 100.00 141.42 100.00 141.42
        Nunchuk/Shake/X = `Click 2`
        Nunchuk/Shake/Y = `Click 2`
        Nunchuk/Shake/Z = `Click 2`
      '';

      xdg.configFile."dolphin-emu/Profiles/Wiimote/NSMBWKeyboard.ini".text = ''
        [Profile]
        Device = XInput2/0/Virtual core pointer
        Buttons/A = A
        Buttons/B = S
        Buttons/1 = Z
        Buttons/2 = X
        Buttons/- = Q
        Buttons/+ = E
        Buttons/Home = Return
        D-Pad/Up = Up
        D-Pad/Down = Down
        D-Pad/Left = Left
        D-Pad/Right = Right
        IR/Up = `Cursor Y-`
        IR/Down = `Cursor Y+`
        IR/Left = `Cursor X-`
        IR/Right = `Cursor X+`
        Shake/X = Shift
        Shake/Y = Shift
        Shake/Z = Shift
        IRPassthrough/Object 1 X = `IR Object 1 X`
        IRPassthrough/Object 1 Y = `IR Object 1 Y`
        IRPassthrough/Object 1 Size = `IR Object 1 Size`
        IRPassthrough/Object 2 X = `IR Object 2 X`
        IRPassthrough/Object 2 Y = `IR Object 2 Y`
        IRPassthrough/Object 2 Size = `IR Object 2 Size`
        IRPassthrough/Object 3 X = `IR Object 3 X`
        IRPassthrough/Object 3 Y = `IR Object 3 Y`
        IRPassthrough/Object 3 Size = `IR Object 3 Size`
        IRPassthrough/Object 4 X = `IR Object 4 X`
        IRPassthrough/Object 4 Y = `IR Object 4 Y`
        IRPassthrough/Object 4 Size = `IR Object 4 Size`
        IMUAccelerometer/Up = `Accel Up`
        IMUAccelerometer/Down = `Accel Down`
        IMUAccelerometer/Left = `Accel Left`
        IMUAccelerometer/Right = `Accel Right`
        IMUAccelerometer/Forward = `Accel Forward`
        IMUAccelerometer/Backward = `Accel Backward`
        IMUGyroscope/Pitch Up = `Gyro Pitch Up`
        IMUGyroscope/Pitch Down = `Gyro Pitch Down`
        IMUGyroscope/Roll Left = `Gyro Roll Left`
        IMUGyroscope/Roll Right = `Gyro Roll Right`
        IMUGyroscope/Yaw Left = `Gyro Yaw Left`
        IMUGyroscope/Yaw Right = `Gyro Yaw Right`
        Nunchuk/Buttons/C = Control_L
        Nunchuk/Buttons/Z = Shift_L
        Nunchuk/Stick/Up = W
        Nunchuk/Stick/Down = S
        Nunchuk/Stick/Left = A
        Nunchuk/Stick/Right = D
        Nunchuk/Stick/Calibration = 100.00 141.42 100.00 141.42 100.00 141.42 100.00 141.42
        Nunchuk/Shake/X = `Click 2`
        Nunchuk/Shake/Y = `Click 2`
        Nunchuk/Shake/Z = `Click 2`
        Options/Sideways Wiimote = True
      '';
    }
  ];
}
