let
  inventory = import ./keys.nix;

  sanitize =
    value:
    builtins.replaceStrings [ "-" "." "/" " " ] [ "_" "_" "_" "_" ] value;

  escapeSingle =
    value:
    builtins.replaceStrings [ "'" ] [ "''" ] value;

  quote =
    value:
    "'${escapeSingle value}'";

  editorsCfg = if inventory ? editors then inventory.editors else { };
  hostsCfg = if inventory ? hosts then inventory.hosts else { };
  rulesCfg = if inventory ? creationRules then inventory.creationRules else [ ];

  mkEntries =
    kind: cfg:
    map (
      name:
      let
        value = cfg.${name};
        recipient =
          if value ? recipient && value.recipient != "" then
            value.recipient
          else
            throw "secrets/keys.nix: ${kind} '${name}' is missing a recipient";
      in
      {
        inherit kind name recipient;
        anchor = "${kind}_${sanitize name}";
        description = if value ? description then value.description else null;
      }
    ) (builtins.attrNames cfg);

  editors = mkEntries "editor" editorsCfg;
  hosts = mkEntries "host" hostsCfg;
  entries = editors ++ hosts;

  _hasRecipients =
    if entries == [ ] then
      throw "secrets/keys.nix: define at least one editor or host recipient"
    else
      true;

  findEntry =
    entriesList: kind: name:
    let
      matches = builtins.filter (entry: entry.name == name) entriesList;
    in
    if matches == [ ] then
      throw "secrets/keys.nix: creationRules references unknown ${kind} '${name}'"
    else
      builtins.head matches;

  resolveNames =
    field: cfg: rule:
    if builtins.hasAttr field rule then
      builtins.getAttr field rule
    else
      builtins.attrNames cfg;

  commentLine =
    entry:
    let
      suffix =
        if entry.description == null || entry.description == "" then
          ""
        else
          " - ${entry.description}";
    in
    "  # ${entry.kind}: ${entry.name}${suffix}";

  keyLines =
    if entries == [ ] then
      [ "keys: []" ]
    else
      [ "keys:" ]
      ++ builtins.concatLists (
        map (entry: [
          (commentLine entry)
          "  - &${entry.anchor} ${entry.recipient}"
        ]) entries
      );

  mkRuleLines =
    rule:
    let
      pathRegex =
        if rule ? pathRegex && rule.pathRegex != "" then
          rule.pathRegex
        else
          throw "secrets/keys.nix: each creation rule needs a non-empty pathRegex";

      editorNames = resolveNames "editors" editorsCfg rule;
      hostNames = resolveNames "hosts" hostsCfg rule;
      extraAgeRecipients = if rule ? extraAgeRecipients then rule.extraAgeRecipients else [ ];
      recipients =
        (map (name: "*${(findEntry editors "editor" name).anchor}") editorNames)
        ++ (map (name: "*${(findEntry hosts "host" name).anchor}") hostNames)
        ++ extraAgeRecipients;

      _hasRuleRecipients =
        if recipients == [ ] then
          throw "secrets/keys.nix: rule '${pathRegex}' resolved to no recipients"
        else
          true;
    in
    [
      "  - path_regex: ${quote pathRegex}"
      "    age:"
    ]
    ++ map (recipient: "      - ${recipient}") recipients;

  ruleLines =
    if rulesCfg == [ ] then
      throw "secrets/keys.nix: define at least one creation rule"
    else
      [ "creation_rules:" ]
      ++ builtins.concatLists (map mkRuleLines rulesCfg);
in
builtins.concatStringsSep "\n" (
  [
    "# This file is generated by ./scripts/generate-sops-config.sh."
    "# Do not edit it by hand. Update ./secrets/keys.nix instead."
    ""
  ]
  ++ keyLines
  ++ [ "" ]
  ++ ruleLines
  ++ [ "" ]
)
